### ISSUE TITLE
Search Field in help center is not available

### ISSUE THREAD

**Issue by AK-Ammo** [onehashai/onehash-chat#25]
### Describe the bug

![scrnli_12_19_2023_12-07-22 PM](https://github.com/onehashai/onehash-chat/assets/130673651/66c96912-fdb5-4c6a-97c7-94cb6e79f513)

### To Reproduce

Check
![scrnli_12_19_2023_12-07-22 PM](https://github.com/onehashai/onehash-chat/assets/130673651/1e8a3dd1-47a0-4bab-aec0-01e1a996f878)

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by rishabh-onehashai** [comment]
![Screenshot from 2024-01-29 11-56-49](https://github.com/onehashai/onehash-chat/assets/138438522/916fe6fe-61a4-4d2e-ac95-fab701beb437)

**Comment by kalpitsahu22** [comment]
***@***.***

**Comment by rishabh-onehashai** [comment]
Color Parsing Issue. Fixed
