### ISSUE TITLE
SSO Login Issue

### ISSUE THREAD

**Issue by AK-Ammo** [onehashai/onehash-chat#76]
### Describe the bug

When client registers for SSO, it says email already exists. 
When he goes for login, it says verification link has been sent to your email. But on checking mail was not found in either inbox or spam folder.
Email: **_nicw@2nent.co.uk_**

### To Reproduce

SSO

### Environment

app.chatwoot.com

### Cloud Provider

None

### Platform

None

**Comment by rishabh-onehashai** [comment]
@AK-Ammo Fixed. Email was under suppressed list in mail server.
